config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  concern :paginable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  scope path_names: { new: 'nouveau', edit: 'modifier' } do
    namespace :admin do
      resources :teachings, path: 'enseignements',
                            except: [:show]
      resources :teaching_cycles, only: [:show],
                                  path: 'enseignements',
                                  shallow: true do
        resources :themes, except: [:index] do
          resources :expectations, only: [:new, :create, :edit, :update,
                                          :destroy],
                                   path: 'attendus'
          post 'classer', to: 'themes#sort', as: :sort, on: :collection
        end
        resources :ability_sets, path: 'competences', except: [:show, :index]
        post 'competences/classer', to: 'ability_sets#sort',
                                    as: :sort_ability_sets
      end
      resources :cycles, except: [:show]
      resources :core_components, except: [:show], path: 'socle'
      post 'cycles/classer', to: 'cycles#sort', as: :sort_cycles
      post 'niveaux/classer', to: 'levels#sort', as: :sort_levels
      resources :users, only: [:index, :edit, :update, :destroy],
                        path: 'utilisateurs', concerns: :paginable
      resources :schools, path: 'etablissements', concerns: :paginable
      patch 'etablissements/:school_id/professeurs/:teacher_id' => 'school_teachers#update', as: :school_teacher
      delete 'etablissements/:school_id/professeurs/:teacher_id' => 'school_teachers#destroy'
    end

    namespace :teacher, path: 'professeur' do
      concern :editable do |options|
        resources :authorships, { path: 'auteurs', only: [:index, :new, :create, :destroy] }.merge(options)
      end

      resources :teaching_cycles, path: 'referentiels', only: [:index],
                                  shallow: true do
        concerns :paginable
        resources :ability_sets, path: 'competences', only: [:index]
        resources :themes, only: [:index]
      end

      resources :school_teachers, path: 'trouver-etablissement',
                               only: [:new, :create, :update, :destroy]
      resources :schools, path: 'etablissement',
                          only: [:new, :create, :show],
                          shallow: true do
        resources :classrooms, except: [:index], path: 'classes',
                               shallow: true do
          resources :students, path: 'eleves', except: [:index, :show]
        end
      end

      patch '/eleves/:id/motdepasse' => 'student_passwords#update', as: :student_password

      resources :groups, path: 'groupes', shallow: true, except: :index do
        resources :chapters, path: 'chapitres', only: [:new, :create] do
          collection do
            post 'classer' => 'chapters#sort', as: :sort
          end
        end
        resources :messages, only: [:create, :destroy]
      end

      get 'niveaux/:id/eleves' => 'student_groups#index'

      resources :chapters, path: 'chapitres', except: [:index, :new, :create] do
        resources :assignments, path: 'exercices', except: [:index] do
          resources :student_exercise_forms, only: :show, as: :result
        end
      end

      get 'chapitres/:id/cours' => 'chapter_lessons#edit', as: :chapter_lessons
      patch 'chapitres/:id/cours' => 'chapter_lessons#update'

      resources :lessons, path: 'cours' do
        concerns :editable, editable_type: 'Lesson'
        concerns :paginable
        resources :steps, path: 'seances', except: [:index, :show], shallow: true
        get 'chercher(/page/:page)', to: 'shared_lessons#index',
                                     as: :search, on: :collection
        get 'apercu', to: 'shared_lessons#show', as: :preview, on: :member
        post 'copier', to: 'shared_lessons#create', as: :copy
        resources :lesson_chapters, only: [:new, :create], as: :chapter,
                                    path: 'partage'
      end

      resources :exercises, path: 'exercices' do
        concerns :editable, editable_type: 'Exercise'
        concerns :paginable
        resources :questions, except: [:index, :show], shallow: true do
          get 'reponses', to: 'answers#index', as: :answers, on: :member
          patch 'reponses', to: 'answers#update', on: :member
        end
        get 'chercher(/page/:page)', to: 'shared_exercises#index', as: :search, on: :collection
        post 'copier', to: 'shared_exercises#create', as: :copy
        resources :exercise_assignments, only: [:new, :create], as: :assignment,
                                         path: 'partage'
      end

      get '/exercices/:id/tester' => 'exercise_forms#new', as: :try_exercise
      post '/exercices/:id/tester' => 'exercise_forms#create'
      get '/exercices/:exercise_id/resultats/:id' => 'exercise_forms#show', as: :exercise_result

      resource :preferences, only: [:update]
    end

    namespace :student, path: 'eleve' do
      resources :groups, path: 'groupes', only: :show do
        resources :messages, only: [:create]
      end

      resources :chapter_lessons, path: 'cours', only: :show
      resources :assignments, path: 'exercices', only: :show, shallow: true do
        resources 'student_exercise_forms', only: [:new, :create, :show],
                                            as: :exercise_forms,
                                            path: 'mes-exercices'
      end
      resources :chapters, path: 'chapitres', only: :show
    end

    authenticated :account do
      root to: 'home#user'
    end
    root to: 'home#guest'

    resources :public_schools, path: 'etablissements', only: [:new, :create]

    devise_for :accounts, path: '',
                          path_names: {
                            sign_in: 'connexion',
                            sign_out: 'deconnexion',
                            registration: 'inscription',
                            password: 'motdepasse',
                            unlock: 'deblocage',
                            sign_up: 'nouveau',
                            cancel: 'annuler'
                          },
                          controllers: {
                            sessions: 'accounts/sessions',
                            registrations: 'accounts/registrations',
                            confirmations: 'accounts/confirmations',
                            passwords: 'accounts/passwords',
                            unlocks: 'accounts/unlocks'
                          }
  end

  get '/pays/:country_id' => 'school_wizard#states'
  get '/pays/:country_id/dpt/:state_id' => 'school_wizard#cities'
  get '/pays/:country_id/dpt/:state_id/ville/:city_id' => 'school_wizard#schools'

  authenticate :account, -> (account) { account.user.admin? } do
    mount Sidekiq::Web, at: '/admin/sidekiq'
  end

  mount ActionCable.server => "/cable"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def guest
    redirect_to root_url if account_signed_in?
  end

  def user
    redirect_to root_url unless account_signed_in?
  end
end

app/views/home/guest.html.erb
<div id="homepage-title">
  <div class="hero">
    <div class="brand">
      <%= inline_svg('shoshin_horizontal.svg') %>
      <h2 class="logo-subtitle">Plateforme pédagogique</h2>
    </div>
    <div class="actions">
      <%= link_to 'Inscription', new_account_registration_path, class: 'btn secondary' %>
      <%= link_to 'Connexion', new_account_session_path, class: 'btn secondary' %>
    </div>
  </div>
</div>
<div id="presentation">
  <h3>Présentation</h3>
  <p>
    Pensée par des professeurs, Shoshin est le fruit d'un travail collectif visant à moderniser, simplifier et améliorer la relation entre les différents acteurs de l'éducation que sont les professeurs, les élèves et les parents.
  </p>
  <p>
  Cette plateforme en ligne est un projet <strong>libre</strong> et <strong>gratuit</strong> destiné aux établissements scolaires français, en France comme à l'étranger, et peut être utilisé <strong>du primaire au lycée</strong>. Le maintien de Shoshin est assuré par <%= link_to 'Ta\'lim', 'http://talim.solutions/fr', target: '_blank' %>.
  </p>
  <p>
    Shoshin est un terme japonais qui signifie « esprit du débutant », utilisé dans le bouddhisme zen et dans les arts martiaux. C'est une attitude d'humilité que le pratiquant doit conserver tout au long de sa progression, quel que soit le niveau atteint.
  </p>
</div>
<div id="quote">
  <blockquote>
    <p>L'esprit du débutant contient beaucoup de possibilités, mais celui de l'expert en contient peu.</p>
    <footer>
      Shunryu Suzuki
    </footer>
  </blockquote>
</div>
<div id="teachers">
  <h3>Enseignants</h3>
  <div class="row item-stretch-s">
    <div class="image column xs12 s4 l3">
    </div>
    <div class="column xs12 s8 l9 description">
      <div class="row">
        <div class="column xs12 l4">
          <p class="description-item">
            Shoshin est une <strong>plateforme collaborative</strong>. Vous pouvez travailler seul ou à plusieurs sur la création de cours et exercices, partager vos ressources, ou encore vous inspirer de celles créées par des collègues.
          </p>
        </div>
        <div class="column xs12 l4">
          <p class="description-item">
            Shoshin est un <strong>espace numérique de travail</strong>. Créez vos classes, organisez votre contenu et décidez quand, comment et pendant combien de temps vos élèves y auront accès.
          </p>
        </div>
        <div class="column xs12 l4">
          <p class="description-item">
            Shoshin est un outil d'<strong>évaluation</strong>. À partir de différents types d'exercices, vous pouvez lier le niveau d'acquisition des compétences et capacités en fonction du taux de réussite de vos élèves.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="students">
  <h3>Élèves</h3>
  <div class="row item-stretch-s">
    <div class="image column xs12 s4 l3">
    </div>
    <div class="column xs12 s8 l9 description">
      <div class="row">
        <div class="column xs12 l4">
          <p class="description-item">
          <strong>Un seul endroit</strong> pour toutes vos disciplines. Retrouvez-les dans un espace réunissant de manière organisée vos cours, exercices et évaluations.
          </p>
        </div>
        <div class="column xs12 l4">
          <p class="description-item">
            Faites un <strong>bilan</strong> en quelques clics, déterminez facilement quels sont les points que vous devez travailler, et accédez rapidement aux ressources mises à disposition par votre professeur pour progresser.
          </p>
        </div>
        <div class="column xs12 l4">
          <p class="description-item">
          Amenez vos cours avec vous. Le site est optimisé pour les smartphones, tablettes et ordinateurs. <strong>Plus de livres</strong> lourds et encombrants, Shoshin vous offre la possibilité de travailler de n'importe où!
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="parents">
  <h3>Parents</h3>
  <div class="row item-stretch-s">
    <div class="image column xs12 s4 l3">
    </div>
    <div class="column xs12 s8 l9 description">
      <div class="row">
        <div class="column xs12 l4">
          <p class="description-item">
          À l'aide d'une interface simple, Shoshin vous présente l'<strong>évolution</strong> de vos enfants dans chaque discipline d'une manière claire afin que vous puissiez réellement accompagner leur scolarité.
          </p>
        </div>
        <div class="column xs12 l4">
          <p class="description-item">
            Un accompagnement en <strong>temps réel</strong>. Paramétrez et recevez une notification quand votre enfant a un devoir à faire, quand une évaluation approche, ou quand il est évalué.
          </p>
        </div>
        <div class="column xs12 l4">
          <p class="description-item">
          Gardez le <strong>contact</strong> avec l'équipe pédagogique qui suit votre enfant, grâce à une messagerie interne gérée par l'établissement scolaire.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="getinvolved">
  <h2>Comment contribuer?</h2>
  <ul>
    <li>Vous êtes enseignant ? <%= link_to 'Créer votre compte', new_account_registration_path %> gratuitement.</li>
    <li>Parlez-en autour de vous ou téléchargez notre <%= link_to 'brochure de présentation', 'https://s3-sa-east-1.amazonaws.com/shoshin-bucket/pdf/Presentation+Shoshin.pdf', target: '_blank' %>.</li>
    <li>Aidez nous à développer notre <%= link_to 'Wiki', 'https://github.com/TalimSolutions/shoshin/wiki/Accueil', target: '_blank' %> en y ajoutant des guides d'utilisation, des tutoriels.</li>
    <li>Vous avez des idées pour améliorer la plateforme ou vous avez rencontré un bug? Créez un <%= link_to 'Ticket', 'https://github.com/TalimSolutions/shoshin/issues', target: '_blank' %>.</li>
    <li>Vous avez des compétences en informatique? Notre code est disponible sur <%= link_to 'GitHub', 'https://github.com/TalimSolutions/shoshin', target: '_blank' %>.</li>
    <li>Vous souhaitez apporter un soutien financier à la plateforme? <%= link_to 'Écrivez-nous', 'mailto:info@talim.solutions' %>.</li>
  </ul>
</div>
<div id="footer">
  <div class="brand">
    <%= inline_svg 'shoshin_vertical.svg' %> est soutenu par :
  </div>
  <div class="sponsor">
    <%= image_tag 'talim.png' %>
    <%= link_to 'www.talim.solutions', 'http://talim.solutions/fr', target: '_blank' %>
  </div>
</div>

app/views/home/user.html.erb
<% content_for :title, 'Accueil' %>
<div class="row">
  <div class="column">
    <div class="card">
      <div class="content-area">
        <p>
          Bonjour <%= current_account.full_name %>
        </p>
      </div>
    </div>
  </div>
</div>