config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  concern :paginable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  scope path_names: { new: 'nouveau', edit: 'modifier' } do
    namespace :admin do
      resources :teachings, path: 'enseignements',
                            except: [:show]
      resources :teaching_cycles, only: [:show],
                                  path: 'enseignements',
                                  shallow: true do
        resources :themes, except: [:index] do
          resources :expectations, only: [:new, :create, :edit, :update,
                                          :destroy],
                                   path: 'attendus'
          post 'classer', to: 'themes#sort', as: :sort, on: :collection
        end
        resources :ability_sets, path: 'competences', except: [:show, :index]
        post 'competences/classer', to: 'ability_sets#sort',
                                    as: :sort_ability_sets
      end
      resources :cycles, except: [:show]
      resources :core_components, except: [:show], path: 'socle'
      post 'cycles/classer', to: 'cycles#sort', as: :sort_cycles
      post 'niveaux/classer', to: 'levels#sort', as: :sort_levels
      resources :users, only: [:index, :edit, :update, :destroy],
                        path: 'utilisateurs', concerns: :paginable
      resources :schools, path: 'etablissements', concerns: :paginable
      patch 'etablissements/:school_id/professeurs/:teacher_id' => 'school_teachers#update', as: :school_teacher
      delete 'etablissements/:school_id/professeurs/:teacher_id' => 'school_teachers#destroy'
    end

    namespace :teacher, path: 'professeur' do
      concern :editable do |options|
        resources :authorships, { path: 'auteurs', only: [:index, :new, :create, :destroy] }.merge(options)
      end

      resources :teaching_cycles, path: 'referentiels', only: [:index],
                                  shallow: true do
        concerns :paginable
        resources :ability_sets, path: 'competences', only: [:index]
        resources :themes, only: [:index]
      end

      resources :school_teachers, path: 'trouver-etablissement',
                               only: [:new, :create, :update, :destroy]
      resources :schools, path: 'etablissement',
                          only: [:new, :create, :show],
                          shallow: true do
        resources :classrooms, except: [:index], path: 'classes',
                               shallow: true do
          resources :students, path: 'eleves', except: [:index, :show]
        end
      end

      patch '/eleves/:id/motdepasse' => 'student_passwords#update', as: :student_password

      resources :groups, path: 'groupes', shallow: true, except: :index do
        resources :chapters, path: 'chapitres', only: [:new, :create] do
          collection do
            post 'classer' => 'chapters#sort', as: :sort
          end
        end
        resources :messages, only: [:create, :destroy]
      end

      get 'niveaux/:id/eleves' => 'student_groups#index'

      resources :chapters, path: 'chapitres', except: [:index, :new, :create] do
        resources :assignments, path: 'exercices', except: [:index] do
          resources :student_exercise_forms, only: :show, as: :result
        end
      end

      get 'chapitres/:id/cours' => 'chapter_lessons#edit', as: :chapter_lessons
      patch 'chapitres/:id/cours' => 'chapter_lessons#update'

      resources :lessons, path: 'cours' do
        concerns :editable, editable_type: 'Lesson'
        concerns :paginable
        resources :steps, path: 'seances', except: [:index, :show], shallow: true
        get 'chercher(/page/:page)', to: 'shared_lessons#index',
                                     as: :search, on: :collection
        get 'apercu', to: 'shared_lessons#show', as: :preview, on: :member
        post 'copier', to: 'shared_lessons#create', as: :copy
        resources :lesson_chapters, only: [:new, :create], as: :chapter,
                                    path: 'partage'
      end

      resources :exercises, path: 'exercices' do
        concerns :editable, editable_type: 'Exercise'
        concerns :paginable
        resources :questions, except: [:index, :show], shallow: true do
          get 'reponses', to: 'answers#index', as: :answers, on: :member
          patch 'reponses', to: 'answers#update', on: :member
        end
        get 'chercher(/page/:page)', to: 'shared_exercises#index', as: :search, on: :collection
        post 'copier', to: 'shared_exercises#create', as: :copy
        resources :exercise_assignments, only: [:new, :create], as: :assignment,
                                         path: 'partage'
      end

      get '/exercices/:id/tester' => 'exercise_forms#new', as: :try_exercise
      post '/exercices/:id/tester' => 'exercise_forms#create'
      get '/exercices/:exercise_id/resultats/:id' => 'exercise_forms#show', as: :exercise_result

      resource :preferences, only: [:update]
    end

    namespace :student, path: 'eleve' do
      resources :groups, path: 'groupes', only: :show do
        resources :messages, only: [:create]
      end

      resources :chapter_lessons, path: 'cours', only: :show
      resources :assignments, path: 'exercices', only: :show, shallow: true do
        resources 'student_exercise_forms', only: [:new, :create, :show],
                                            as: :exercise_forms,
                                            path: 'mes-exercices'
      end
      resources :chapters, path: 'chapitres', only: :show
    end

    authenticated :account do
      root to: 'home#user'
    end
    root to: 'home#guest'

    resources :public_schools, path: 'etablissements', only: [:new, :create]

    devise_for :accounts, path: '',
                          path_names: {
                            sign_in: 'connexion',
                            sign_out: 'deconnexion',
                            registration: 'inscription',
                            password: 'motdepasse',
                            unlock: 'deblocage',
                            sign_up: 'nouveau',
                            cancel: 'annuler'
                          },
                          controllers: {
                            sessions: 'accounts/sessions',
                            registrations: 'accounts/registrations',
                            confirmations: 'accounts/confirmations',
                            passwords: 'accounts/passwords',
                            unlocks: 'accounts/unlocks'
                          }
  end

  get '/pays/:country_id' => 'school_wizard#states'
  get '/pays/:country_id/dpt/:state_id' => 'school_wizard#cities'
  get '/pays/:country_id/dpt/:state_id/ville/:city_id' => 'school_wizard#schools'

  authenticate :account, -> (account) { account.user.admin? } do
    mount Sidekiq::Web, at: '/admin/sidekiq'
  end

  mount ActionCable.server => "/cable"
end

app/controllers/teacher/ability_sets_controller.rb
class Teacher::AbilitySetsController < TeacherController
  def index
    @teaching_cycle = TeachingCycle.includes(ability_sets: :ability_items).find(params[:teaching_cycle_id]) 
  end
end

app/controllers/teacher/answers_controller.rb
class Teacher::AnswersController < TeacherController
  before_action :load_question # sets @question
  before_action :authorize_author

  def index
  end

  def update
    if @question.update(answers_params)
      redirect_to teacher_exercise_path(@question.exercise)
    else
      render :index
    end
  end

  private

  def answers_params
    case @question.print_type
    when 'input'
      params.require('questions_input').permit(answers_attributes: [:id, :content, :_destroy])
    when 'single_choice'
      params.require('questions_single_choice').permit(answers_attributes: [:id, :content, :correct, :_destroy])
    when 'multiple_choice'
      params.require('questions_multiple_choice').permit(answers_attributes: [:id, :content, :correct, :_destroy])
    when 'classify'
      params.require('questions_classify').permit(answers_attributes: [:id, :name, :_destroy, category_items_attributes: [:id, :content, :_destroy]])
    when 'association'
      params.require('questions_association').permit(answers_attributes: [:id, :left, :right, :_destroy])
    when 'file_upload'
      params.require('questions_file_upload').permit(answers_attributes: [:id, :file_format, :_destroy])
    end
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_author
    redirect_to [:teacher, @question.exercise] unless current_user.in? @question.authors
  end
end

app/controllers/teacher/assignments_controller.rb
class Teacher::AssignmentsController < TeacherController
  before_action :authorize
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_action :set_exercises, except: [:show, :destroy]

  def show
  end

  def new
    @assignment = @chapter.assignments.new
  end

  def create
    @assignment = @chapter.assignments.new(create_params)
    if @assignment.save
      flash[:notice] = 'Exercice ajouté.'
      redirect_to [:teacher, @chapter]
    else
      render :new
    end
  end

  def edit
    @exercises.unshift(@assignment.exercise)
  end

  def update
    if @assignment.update(update_params)
      flash[:notice] = 'Exercice mis à jour.'
      redirect_to [:teacher, @chapter]
    else
      render :edit
    end
  end

  def destroy
    @assignment.destroy
    flash[:notice] = 'Exercice supprimé.'
    redirect_to [:teacher, @chapter]
  end

  private

  def authorize
    @chapter = Chapter.includes(group: :level).find(params[:chapter_id])
    redirect_to root_url unless current_user == @chapter.teacher
  end

  def set_assignment
    @assignment = Assignment.find_by(chapter: @chapter,
                                                exercise_id: params[:id])
  end

  def create_params
    params.require(:assignment).permit(:exercise_id, :max_tries, :due_date)
  end

  def update_params
    params.require(:assignment).permit(:max_tries, :due_date, ability_evaluations: @assignment&.questions.map { |question| { question.id.to_s => [] } }, expectation_evaluations: @assignment&.questions.map { |question| { question.id.to_s => [] } })
  end

  def set_exercises
    @exercises = current_user.exercises_from_level(@chapter.level) - @chapter.exercises
  end
end

app/controllers/teacher/authorships_controller.rb
class Teacher::AuthorshipsController < TeacherController
  before_action :set_editable
  before_action :restrict_to_authors

  def index
  end

  def new
  end

  def create
    @editable.authorships.create(authorship_params)
    render :index
  end

  def destroy
    @editable.authorships.find(params[:id]).destroy
    if @editable.reload.authorships.any?
      redirect_to([:teacher, @editable, :authorships])
    else
      @editable.destroy
      redirect_to([:teacher, :lessons])
    end
  end

  private

  def restrict_to_authors
    redirect_to [:teacher, :lessons] unless current_user.in? @editable.authors
  end

  def set_editable
    case params[:editable_type]
    when 'Lesson'
      @editable = Lesson.includes(:authors).find(params[:lesson_id])
    when 'Exercise'
      @editable = Exercise.includes(:authors).find(params[:exercise_id])
    end
  end

  def authorship_params
    params.require(:authorship).permit(:teacher_id)
  end
end

app/controllers/teacher/chapter_lessons_controller.rb
class Teacher::ChapterLessonsController < TeacherController
  before_action :authorize

  def edit
  end

  def update
    params[:chapter] ||= { lesson_ids: [] }
    if @chapter.update(lessons: @lessons.where(id: params[:chapter][:lesson_ids]))
      flash[:notice] = 'Liste de cours mise à jour.'
      redirect_to [:teacher, @chapter]
    else
      render :edit
    end
  end

  private

  def authorize
    @chapter = Chapter.includes(group: :level).find(params[:id])
    redirect_to root_url unless current_user == @chapter.teacher
    @lessons = current_user.lessons_from_level(@chapter.level)
  end
end

app/controllers/teacher/chapters_controller.rb
class Teacher::ChaptersController < TeacherController
  before_action :authorize_on_group, only: [:new, :create, :sort]
  before_action :authorize_on_chapter, except: [:new, :create, :sort]

  def show
  end

  def new
    @chapter = @group.chapters.new
  end

  def create
    @chapter = @group.chapters.new(chapter_params)
    if @chapter.save
      flash[:notice] = 'Chapitre créé.'
      redirect_to [:teacher, @chapter]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @chapter.update(chapter_params)
      flash[:notice] = 'Chapitre mis à jour.'
      redirect_to [:teacher, @chapter]
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy
    flash[:notice] = 'Chapitre supprimé.'
    redirect_to [:teacher, @chapter.group]
  end

  def sort
    params[:chapter].each_with_index do |id, index|
      @group.chapters.find(id).update(position: index + 1)
    end
    head :ok
  end

  private

  def chapter_params
    params.require(:chapter).permit(:name)
  end

  def authorize_on_group
    @group = Group.includes(:teacher).find(params[:group_id])
    redirect_to root_url unless current_user == @group.teacher
  end

  def authorize_on_chapter
    @chapter = Chapter.includes(group: :teacher).find(params[:id])
    redirect_to root_url unless current_user == @chapter.group.teacher
  end
end

app/controllers/teacher/classrooms_controller.rb
class Teacher::ClassroomsController < TeacherController
  before_action :authorize_based_on_classroom, only: [:show, :edit, :update,
                                                      :destroy]
  before_action :authorize_based_on_school, only: [:new, :create]

  def show
    @classroom = Classroom.find(params[:id])
  end

  def new
    @classroom = @school.classrooms.new
  end

  def create
    @classroom = @school.classrooms.new(classroom_params)
    if @classroom.save
      flash[:notice] = 'Classe ajoutée.'
      redirect_to [:teacher, @classroom]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @classroom.update(classroom_params)
      flash[:notice] = 'Classe mise à jour.'
      redirect_to [:teacher, @classroom]
    else
      render :edit
    end
  end

  def destroy
    if @classroom.students.any?
      flash.now[:notice] = 'Vous ne pouvez pas supprimer une classe qui contient des élèves.'
    else
      @classroom.destroy
      flash.now[:notice] = 'Classe supprimée.'
    end
  end

  private

  def classroom_params
    params.require(:classroom).permit(:name, :level_id)
  end

  def authorize_based_on_classroom
    @classroom = Classroom.includes(:level, :school)
                          .find(params[:id])
    redirect_to root_url unless current_user.in? @classroom.school.teachers
  end

  def authorize_based_on_school
    @school = School.find(params[:school_id])
    redirect_to root_url unless current_user.in? @school.teachers
  end
end

app/controllers/teacher/exercise_assignments_controller.rb
class Teacher::ExerciseAssignmentsController < TeacherController
  before_action :authorize
  before_action :set_groups

  def new
    @assignment = @exercise.assignments.new
  end

  def create
    @assignment = @exercise.assignments.new(assignment_params)
    if @assignment.save
      flash[:notice] = 'Exercice ajouté au groupe'
      redirect_to [:teacher, @exercise]
    else
      render :new
    end
  end

  private

  def authorize
    @exercise = Exercise.includes(:authors).find(params[:exercise_id])
    redirect_to root_url unless current_user.in? @exercise.authors
  end

  def set_groups
    @groups = current_user.groups.includes(:level, :teaching, :chapters)
  end

  def assignment_params
    params.require(:assignment).permit(:chapter_id)
  end
end

app/controllers/teacher/exercise_forms_controller.rb
class Teacher::ExerciseFormsController < TeacherController
  before_action :authorize_exercise, only: [:new, :create]
  before_action :authorize_exercise_form, only: [:show]

  def new
    @exercise_form = current_user.user_exercise_forms.new(exercise: @exercise)
  end

  def create
    @exercise_form = current_user.user_exercise_forms.new(exercise: @exercise)
    @exercise_form.answers = answer_attributes
    @exercise_form.auto_correct
    @exercise_form.save
    redirect_to teacher_exercise_result_path(@exercise, @exercise_form)
  end

  def show
  end

  private

  def authorize_exercise
    @exercise = Exercise.includes(:questions).find(params[:id])
    redirect_to root_url unless @exercise.is_accessible_by(current_user)
  end

  def authorize_exercise_form
    @exercise_form = UserExerciseForm.includes(exercise: :questions).find(params[:id])
    redirect_to root_url unless current_user == @exercise_form.user
  end

  def answer_attributes
    white_listed = []
    @exercise_form.questions.each do |question|
      if question.class == Questions::MultipleChoice
        white_listed << { question.id.to_s => [] }
      elsif question.class == Questions::Association
        white_listed << { question.id.to_s => question.answers.map { |answer| answer.id.to_s } }
      elsif question.class == Questions::Classify
        white_listed << { question.id.to_s => question.category_items.map { |item| item.id.to_s } }
      else
        white_listed << question.id.to_s
      end
    end
    params.require(:answers).permit(white_listed)
  end
end

app/controllers/teacher/preferences_controller.rb
class Teacher::PreferencesController < TeacherController
  def update
    current_user.update(preferences_params)
    flash[:notice] = 'Préférences mises à jour.'
    redirect_to edit_account_registration_path
  end

  private

  def preferences_params
    params.require(:teacher).permit(preferences: [:level_id, :teaching_id])
  end
end

app/views/teacher/exercises/_form.html.erb
<%= simple_form_for [:teacher, @exercise], defaults: { required: false } do |f| %>
  <div class="content-area">
    <%= f.input :name, label: 'Titre de l\'exercice' %>
    <%= f.association :teaching, collection: Teaching.ordered, label: 'Enseignement' %>
    <div class="input">
      <label>Niveaux</label>
      <%= f.association :levels, collection: Level.all, as: :check_boxes, label: false, include_hidden: false %>
    </div>
    <%= f.input :time, collection: (1..12).map { |k| k*5 }, label_method: ->(time) { "#{time} minutes" }, label: 'Durée' %>
    <%= f.input :difficulty, collection: [['Facile', 1], ['Moyen', 2], ['Difficile', 3]], as: :radio_buttons, label: 'Difficulté' %>
    <%= f.input :statement, as: :hidden, label: 'Énoncé (optionnel)' %>
    <trix-editor input="exercise_statement" class="trix-content"></trix-editor>
    <%= f.input :exam, as: :radio_buttons, label: 'Sujet d\'annale ?' %>
    <%= f.input :shared, as: :radio_buttons, label: 'Partagé ?' %>
  </div>
  <div class="actions-area">
    <%= f.button :submit, 'Enregistrer' %>
  </div>
<% end %>

app/views/teacher/exercises/edit.html.erb
<% content_for :title, "Modifier un exercice" %>
<% content_for :parent_url, url_for([:teacher, @exercise]) %>
<div class="row">
  <div class="column xs12 l8 offset-l2">
    <div class="card">
      <div class="title-area">
        <h3 class="main-title">Modifier un exercice</h3>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/teacher/exercises/index.html.erb
<% content_for :title, "Exercices" %>
<div class="row">
  <div class="column xs12 l3">
    <div class="row">
      <div class="column xs12 s8 m12">
        <div class="card">
          <div class="title-area">
            <h3 class="main-title">Filtrer</h3>
          </div>
          <%= search_form_for @q, url: [:teacher, :exercises], defaults: { required: false } do |f| %>
          <div class="content-area">
            <div class="row">
              <div class="column xs12 s6 l12">
                <%= f.input :name_cont, label: 'Titre' %>
              </div>
              <div class="column xs12 s3 l12">
                <%= f.input :teaching_id_eq, collection: Teaching.ordered, label: 'Enseignement' %>
              </div>
              <div class="column xs12 s3 l12">
                <%= f.input :editable_levels_level_id_eq, collection: Level.all, label: 'Niveau' %>
              </div>
            </div>
            <div class="row">
              <div class="column xs12 s6 l12">
                <%= f.input :is_used_true, collection: [['Oui', 1], ['Non', 0]], label: 'Utilisé ?' %>
              </div>
              <div class="column xs12 s6 l12">
                <%= f.input :shared_eq, collection: [['Oui', true], ['Non', false]], label: 'Partagé ?' %>
              </div>
            </div>
          </div>
          <div class="actions-area">
            <%= f.submit 'Filtrer', class: 'btn' %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="column xs12 s4 m12">
        <div class="card">
          <div class="title-area">
            <h3 class="main-title">Besoin d'inspiration?</h3>
          </div>
          <div class="content-area">
            <p>Vous pouvez consulter, copier et modifier les exercices partagés par des collègues.</p>
          </div>
          <div class="actions-area">
            <%= link_to 'Exercices partagés', [:search, :teacher, :exercises], class: 'btn' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="column xs12 l9">
    <div class="card">
      <div class="table-area">
        <div class="header">
          Mes exercices
        </div>
        <div class="table">
          <table>
            <thead>
              <tr>
                <th class="text"><%= sort_link(@q, :name, 'Titre') %></th>
                <th class="text"><%= sort_link(@q, :teaching_name, 'Enseignement') %></th>
                <th class="text"><%= sort_link(@q, :levels_short_name, 'Niveaux') %></th>
                <th class="boolean">Utilisé ?</th>
                <th class="boolean"><%= sort_link(@q, :shared, 'Partagé ?') %></th>
                <th class="actions"></th>
              </tr>
            </thead>
            <tbody>
              <% @exercises.each do |exercise| %>
                <tr>
                  <td class="text"><%= exercise.name %></td>
                  <td class="text"><%= exercise.teaching_short_name %></td>
                  <td class="text"><%= exercise.level_names %></td>
                  <td class="boolean">
                    <%= material_icon.check.css_class('icon-success') if exercise.assignments.any? %>
                  </td>
                  <td class="boolean">
                    <%= material_icon.check.css_class('icon-success') if exercise.shared %>
                  </td>
                  <td class="actions">
                    <%= link_to material_icon.visibility, teacher_try_exercise_path(exercise), class: 'btn' %>
                    <%= link_to material_icon.edit, [:teacher, exercise ], class: 'btn link-edit' %>
                    <%= link_to material_icon.delete, [:teacher, exercise ], method: :delete, data: { confirm: 'En êtes vous sûr ?' }, class: 'btn link-destroy' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="footer">
          <div class="page-info">
            <%= page_entries_info @exercises %>
          </div>
          <%= paginate @exercises %>
        </div>
      </div>
      <div class="actions-area">
        <%= link_to 'Ajouter', new_teacher_exercise_path, class: 'btn'%>
      </div>
    </div>
  </div>
</div>

app/views/teacher/exercises/new.html.erb
<% content_for :title, "Nouvel exercice" %>
<% content_for :parent_url, teacher_exercises_path %>
<div class="row">
  <div class="column xs12 l8 offset-l2">
    <div class="card">
      <div class="title-area">
        <h3 class="main-title">Nouvel exercice</h3>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/teacher/exercises/show.html.erb
<% content_for :title, @exercise.name %>
<% content_for :parent_url, teacher_exercises_path %>
<div class="row">
  <div class="column xs12 l4">
    <div class="card">
      <div class="title-area">
        <h3 class="main-title">Données de l'exercice</h3>
      </div>
      <div class="content-area">
        <strong>Titre :</strong> <%= @exercise.name %><br>
        <strong>Enseignement :</strong> <%= @exercise.teaching_name %><br>
        <strong>Niveaux :</strong> <%= @exercise.level_names %><br>
        <strong>Popularité :</strong> <%= @exercise.popularity %>
      </div>
      <div class="actions-area">
        <%= link_to 'Modifier', [:edit, :teacher, @exercise], class: 'btn' %>
        <%= link_to 'Voir', teacher_try_exercise_path(@exercise), class: 'btn' %>
      </div>
    </div>
  </div>
  <div class="column xs12 s6 l4">
    <div class="card">
      <div class="title-area">
        <h3 class="main-title">Groupes qui ont accès à cet exercice</h3>
      </div>
      <div class="content-area">
        <% if @assignments.any? %>
          <ul>
            <% @assignments.each do |assignment| %>
              <li><%= assignment.chapter.group.display_name %> dans le chapitre <%= assignment.chapter.name %></li>
            <% end %>
          </ul>
        <% else %>
          <p>Vous n'utilisez pas encore cet exercice avec l'un de vos groupes.</p>
        <% end %>
      </div>
      <div class="actions-area">
        <%= link_to 'Ajouter', new_teacher_exercise_assignment_path(@exercise), class: 'btn' %>
      </div>
    </div>
  </div>
  <div class="column xs12 s6 l4">
    <div class="card">
      <div class="title-area">
        <h3 class="main-title">Auteurs<h3>
      </div>
      <div class="content-area">
        <% @exercise.authors.each do |author| %>
          <div class="user-bar small"> <img src="<%= gravatar_url(author.email) %>" alt="<%= author.full_name %> avatar" /> <span><%= author.full_name %></span></div>
        <% end %>
      </div>
      <div class="actions-area">
        <%= link_to 'Modifier', [:teacher, @exercise, :authorships], class: 'btn' %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="column">
    <div class="card">
      <div class="title-area">
        <h3 class="main-title">Énoncé et questions</h3>
      </div>
      <% if @exercise.statement %>
        <div class="content-area">
          <div class="trix-content">
            <%= @exercise.statement.html_safe %>
          </div>
        </div>
      <% end %>
      <% if @exercise.questions.size == 0 %>
        <div class="content-area">
          <p>
            Cet exercice ne possède pas encore de questions.
          </p>
        </div>
        <% if current_user.in? @exercise.authors %>
          <div class="actions-area">
            <%= link_to 'Ajouter une question', [:new, :teacher, @exercise, :question], class: 'btn link-add' %>
          </div>
        <% end %>
      <% else %>
        <div class="stepper-area">
          <% @exercise.questions.each do |question| %>
            <div class="stepper-bar">
              <span class="stepper-position"><%= question.position %></span>
              <span class="stepper-title">
                <%= question.print_title %>
                <% if current_user.in? @exercise.authors %>
                  <%= link_to material_icon.edit, edit_teacher_question_path(question) %>
                  <%= link_to material_icon.delete, teacher_question_path(question), method: :delete, data: { confirm: 'En êtes vous sûr ?' }, class: 'link-destroy' %>
                <% end %>
              </span>
            </div>
            <div class="stepper-content">
              <div class="trix-content">
                <%= question.content.html_safe %>
              </div>
              <% unless question.print_type == 'redaction' %>
                <div class="answers">
                  <p class="title">Réponses <%= link_to material_icon.edit, answers_teacher_question_path(question) %></p>
                  <div class="row">
                    <% question.answers.each do |answer| %>
                      <%= render answer, answer: answer %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
          <% if current_user.in? @exercise.authors %>
            <a class="stepper-bar adder" href="<%= new_teacher_exercise_question_path(@exercise) %>">
              <span class="stepper-position"><%= material_icon.add %></span>
              <span class="stepper-title">Ajouter</span>
            </a>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>